name: Auto Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "23"
          elixir-version: "1.11.4"

      - name: Install Dependencies
        run: |
          mix deps.get
          mix deps.compile
      - name: Check *.ex, *.exs Files Format
        run: mix format --check-formatted

      - name: Check *.eex Templates Format
        run: |
          cd assets
          npm i
          cd ..
          assets/node_modules/prettier/bin-prettier.js --check .
      - name: Run Test
        run: mix test

      - name: Auto Deploy
        run: |
          sudo pip install gigalixir --ignore-installed six
          gigalixir login -e "${{ secrets.GIGALIXIR_USERNAME }}" -y -p "${{ secrets.GIGALIXIR_PASSWORD }}"
          gigalixir git:remote ${{ secrets.APP_NAME }}
          git push -f gigalixir HEAD:refs/heads/main
      - name: Migration
        run: |
          mkdir ~/.ssh
          printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          gigalixir ps:migrate -a ${{ secrets.APP_NAME }}
